image: $CI_REGISTRY/veyon/veyon:4.2-win64

stages:
  - build

build-win32-installer:
  stage: build
  script:
    - ./prepare-build.sh
    - veyon/.travis/linux.cross.win32/script.sh extra-plugins-nsi
    - mv veyon/build/*.exe .
  artifacts:
    paths: [ "*.exe" ]

build-win64-installer:
  stage: build
  script:
    - ./prepare-build.sh
    - veyon/.travis/linux.cross.win64/script.sh extra-plugins-nsi
    - mv veyon/build/*.exe .
  artifacts:
    paths: [ "*.exe" ]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
