image: $CI_REGISTRY/veyon/ci-mingw-w64:4.2

stages:
  - build

build-win32-installer:
  stage: build
  script:
    - ./prepare-build.sh
    - veyon/.ci/windows/build.sh addons-nsi
    - mv veyon/*.exe .
  artifacts:
    paths: [ "*.exe" ]

build-win64-installer:
  stage: build
  script:
    - ./prepare-build.sh
    - veyon/.ci/windows/build.sh addons-nsi
    - mv veyon/*.exe .
  artifacts:
    paths: [ "*.exe" ]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
