image: $CI_REGISTRY/veyon/ci-mingw-w64:4.5

stages:
  - build

build-win32:
  stage: build
  script:
    - ./prepare-build.sh
    - cd veyon && .ci/windows/build.sh 32 addons-binaries && cd ..
    - mv veyon/veyon-addons-win32* .
  artifacts:
    paths: [ "veyon-addons-win32*" ]

build-win64:
  stage: build
  script:
    - ./prepare-build.sh
    - cd veyon && .ci/windows/build.sh 64 addons-binaries && cd ..
    - mv veyon/veyon-addons-win64* .
  artifacts:
    paths: [ "veyon-addons-win64*" ]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
