image: $CI_REGISTRY/veyon/ci-mingw-w64:4.3

stages:
  - build

build-win32-installer:
  stage: build
  script:
    - ./prepare-build.sh
    - cd veyon && .ci/windows/build.sh 32 addons-nsi && cd ..
    - mv veyon/*.exe .
  artifacts:
    paths: [ "*.exe" ]

build-win64-installer:
  stage: build
  script:
    - ./prepare-build.sh
    - cd veyon && .ci/windows/build.sh 64 addons-nsi && cd ..
    - mv veyon/*.exe .
  artifacts:
    paths: [ "*.exe" ]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
